* Emacs Learning Journal
I have been using vim ever since I started programming. Recently I am planning
to switch to Emacs because I have heard a lot of good things about it. Emacs is
such a beast to tame, so I am writing this note (written in Org mode) to remind
myself of some useful tips and packages I have encountered during the Emacs
learning journey.

** Useful Packages (Dependency not included)
 - Org Mode (built in)
   This note is actually written in Org Mode. It is an awesome plugin for
   keeping notes, maintaining TODO lists, and authoring documents with a fast
   and effective plain text system.
 - Magit
   A plugin dedicated to git version control system.
 - Company
   A front end auto-completion plugin.
   - Company-flow
     Autocompletion fo javascript.
 - Spacemacs-dark theme
   An Emacs theme used by Spacemacs Project.
 - Elpy
   A major mode for python.

 - ace-window
   A handy tool to select windows
 - ivy 
   fuzzy search
 - ace-jump-mode
   Easy to jump to anywhere
 - rainbow-delimiter
 - powerline
 - yasnippets
   - yasnippets-snippets

 - emmet mode
   for html editing

