* Emacs Learning Journal
I have been using vim ever since I started programming. Recently I am planning
to switch to Emacs because I have heard a lot of good things about it. Emacs is
such a beast to tame, so I am writing this note (written in Org mode) to remind
myself of some useful tips and packages I have encountered during the Emacs
learning journey.

** Useful Packages (Dependency not included)
 - Org Mode (built in)
   This note is actually written in Org Mode. It is an awesome plugin for
   keeping notes, maintaining TODO lists, and authoring documents with a fast
   and effective plain text system.
 - Magit
   A plugin dedicated to git version control system.
 - Company
   A front end auto-completion plugin.
   - Company-flow
     Autocompletion fo javascript.
 - Spacemacs-dark theme
   An Emacs theme used by Spacemacs Project.
 - Elpy
   A major mode for python.

 - ace-window
   A handy tool to select windows
 - ivy 
   fuzzy search
 - ace-jump-mode
   Easy to jump to anywhere
 - rainbow-delimiter
 - powerline
 - yasnippets
   - yasnippets-snippets

 - emmet mode
   for html editing
 - AUCtex
   for Latex editing

** Elpy first time setup
 1. Create a new python3 virtualenv and activate it.
#+BEGIN_SRC shell
virtualenv .env
source .env/bin/activate
#+END_SRC

 2. Install all necessary packages for elpy 
#+BEGIN_SRC shell
pip install rope jedi importmagic autopep8 flake8 jupyter yapf black
#+END_SRC

 3. Go to emacs, activate virtualenv and run ~M-x elpy-config~
#+BEGIN_SRC 
M-x pyvenv-workon .env
M-x elpy-config
#+END_SRC

 4. run python script
    1. start a python process by ~M-x run-python~.
    2. use C-c C-c to send code to the ipython console and run it.

** EIN (jupyter notebook on emacs)
 1. Solve plot background problem: put the following to the start of jupyter notebook
#+BEGIN_SRC python
%matplotlib inline
import matplotlib as mpl
mpl.rcParams["figure.facecolor"] = "white"
mpl.rcParams["axes.facecolor"] = "white"
mpl.rcParams["savefig.facecolor"] = "white"
#+END_SRC


** Email setup **
 1. Sending email:
    MSMTP
    
 2. Reading email:
    Notmuch

 3. Fetching email:
    offlineimap

 Installation:
 sudo apt install MSMTP notmuch offlineimap
